[package]
name = "merkle-distributor"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]
name = "merkle_distributor"
path = "src/lib.rs"

[dependencies]
hex = "0.4"
near-contract-standards = "4.0.0-pre.7"
near-sdk = "4.0.0-pre.7"
